---

- name: Enable COPR on dnf 
  dnf:
    name:
    - dnf
    - dnf-plugins-core

- name: Enable wg-portal grillo-delmal/wg-portal
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: grillo-delmal/wg-portal

- name: Prepare services
  dnf:
    name:
    - wg-portal
    - git
    - wireguard-tools
    - net-tools
    state: latest

- name: Folder exists
  file:
    path: "/var/lib/wg-portal/config/"
    state: directory

- name: Upload the config.yml file
  template:
    src: config.yml.j2
    dest: "/var/lib/wg-portal/config/config.yml"
  notify: 
    - 'wgportal : Restart wgportal service'

- name: Start service
  service:
    name: wg-portal.service
    enabled: true
    state: started
