---

- name: Enable COPR on dnf
  ansible.builtin.dnf:
    name:
      - dnf
      - dnf-plugins-core

- name: Enable wg-portal grillo-delmal/wg-portal
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: grillo-delmal/wg-portal

- name: Prepare services
  ansible.builtin.dnf:
    name:
      - wg-portal
      - git
      - wireguard-tools
      - net-tools

- name: Folder exists
  ansible.builtin.file:
    path: "/var/lib/wg-portal/config/"
    state: directory

- name: Upload the config.yml file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "/var/lib/wg-portal/config/config.yml"
  notify:
    - 'wgportal : Restart wgportal service'

- name: Start service
  ansible.builtin.service:
    name: wg-portal.service
    enabled: true
    state: started
