---

- name: Enable COPR on dnf 
  dnf:
    name:
    - dnf
    - dnf-plugins-core

- name: Enable wg-portal grillo-delmal/wg-portal
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: grillo-delmal/wg-portal

- name: Prepare services
  dnf:
    name:
    - wg-portal
    - git
    - wireguard-tools
    - net-tools
    state: latest

- name: Open/udp ports for wg
  ansible.posix.firewalld:
    zone: external
    port: "{{ wgportal_config.ports }}/udp"
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Enable masquerading
  ansible.posix.firewalld:
    zone: external
    masquerade: true
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Set external zone as the default
  shell: |
    if [ "$(firewall-cmd --get-default-zone)" == "external" ] 
    then
      echo "same"
    else
      firewall-cmd --set-default-zone external
    fi
  register: tmp
  changed_when: tmp.stdout != "same" 

- name: Folder exists
  file:
    path: "/var/lib/wg-portal/config/"
    state: directory

- name: Upload the config.yml file
  template:
    src: config.yml.j2
    dest: "/var/lib/wg-portal/config/config.yml"
  notify: 
    - 'wgportal : Restart wgportal service'

- name: Start service
  service:
    name: wg-portal.service
    enabled: true
    state: started
