---

- name: Download mod
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: "/opt/mods/{{ (item.url | urlsplit('path') | split('/'))[-1] }}"
    mode: '0644'
  register: luanti_mod_archive

- name: Install new mod
  when: luanti_mod_archive is changed and not ansible_check_mode
  notify:
    - 'luanti : Restart minetest service'
  block:
    - name: Remove current version of the mod if exist
      ansible.builtin.file:
        path: "{{
            luanti_mine_home
          }}/{{
            luanti_config.world.id
          }}/worldmods/{{
            item.name
          }}"
        state: absent

    - name: World mods folder must exist
      become: true
      become_user: minetest
      ansible.builtin.file:
        path: "{{
            luanti_mine_home
          }}/{{
            luanti_config.world.id
          }}/worldmods{{
            ('/' + item.name) if (item.create_folder | default(false)) else ''
          }}"
        owner: minetest
        group: minetest
        state: directory
        mode: '0755'

    - name: Mods is available
      become: true
      become_user: minetest
      ansible.builtin.unarchive:
        src: "/opt/mods/{{ (item.url | urlsplit('path') | split('/'))[-1] }}"
        dest: "{{
            luanti_mine_home
          }}/{{
            luanti_config.world.id
          }}/worldmods{{
            ('/' + item.name) if (item.create_folder | default(false)) else ''
          }}"
        owner: minetest
        group: minetest
        remote_src: true
