- name: Prepare services
  dnf:
    name:
    - cockpit
    - cockpit-ws
    - cockpit-bridge
    - cockpit-podman
    state: latest

- name: Allow login
  ansible.builtin.copy:
    dest: /etc/cockpit/disallowed-users
    content: ""
  register: config_change

- name: Start cockpit
  service:
    name: cockpit.socket
    state: started
    enabled: True
