---
# Private apps
- name: Setup incus in host machines
  import_playbook: books/incus_machines.yml
- name: Setup containers
  import_playbook: books/incus_containers.yml
- name: Setup basic infrastructure
  import_playbook: books/role_infra.yml
# Public apps
- name: AI related apps
  import_playbook: books/role_ai.yml
- name: General apps
  import_playbook: books/role_apps.yml
- name: Games ^^
  import_playbook: books/role_games.yml
