---
# Private apps
- import_playbook: books/incus_machines.yml
- import_playbook: books/incus_containers.yml
- import_playbook: books/role_dns.yml
- import_playbook: books/role_traefik.yml
- import_playbook: books/role_forgejo.yml
- import_playbook: books/role_semaphore.yml
- import_playbook: books/role_wgportal.yml
# Public apps
- import_playbook: books/role_ai.yml
- import_playbook: books/role_maruchan.yml
- import_playbook: books/role_luanti.yml
- import_playbook: books/role_veloren.yml
- import_playbook: books/role_starbound.yml
- import_playbook: books/role_jupyter.yml