---
# Private apps
- import_playbook: books/setup_servers.yml
- import_playbook: books/build_dns.yml
- import_playbook: books/build_traefik.yml
- import_playbook: books/build_forgejo.yml
- import_playbook: books/build_semaphore.yml
# Public apps
- import_playbook: books/build_ai.yml
- import_playbook: books/build_maruchan.yml
- import_playbook: books/build_luanti.yml
- import_playbook: books/build_veloren.yml