---
# Private apps
- import_playbook: books/incus_machines.yml
- import_playbook: books/incus_containers.yml
- import_playbook: books/role_infra.yml
# Public apps
- import_playbook: books/role_ai.yml
- import_playbook: books/role_apps.yml
- import_playbook: books/role_games.yml
