---
- name: Set to force
  hosts: servers
  tasks:
    - name: Set fact
      set_fact: 
        proxmox_force: False

- import_playbook: books/build_dns.yml
- import_playbook: books/build_ai.yml
- import_playbook: books/build_maruchan.yml