---

- hosts: prox_root
  vars_files: secrets.yml
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: '{{ gateway_ip }}'

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"

    containers:
    - name: ct_maruchan
      vmid: 100
      hostname: "{{ hostvars['ct_maruchan'].ct_hostname }}"
      ip_address: "{{ hostvars['ct_maruchan'].ansible_host }}"
      disk: 'local-lvm:4'
      cores: 1
      memory: 1024

    - name: ct_ai
      vmid: 101
      hostname: "{{ hostvars['ct_maruchan'].ct_hostname }}"
      ip_address: "{{ hostvars['ct_ai'].ansible_host }}"
      disk: 'local-lvm:8'
      cores: 4
      memory: 6144

- hosts: ct_ai
  roles:
  - role: ct_ai

- hosts: ct_maruchan
  roles:
  - role: ct_maruchan
