---

- hosts: app_dns:&servers
  vars_files: secrets.yml
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"
      domain: "{{ homelab_domain }}"

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"
      force: "{{ proxmox_force | default(True) }}"

    containers: "{{ 
      groups['app_dns'] |
        intersect(groups['containers']) |
        map('extract', hostvars) }}"

- hosts: app_dns:&containers
  roles:
  - role: dns
    domain: "{{ homelab_domain }}"
    dns: "{{ homelab_dns }}"
    servers: |
      {{
        groups['servers'] | 
          map('extract', hostvars) | 
          map('dict2items') | 
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) | 
          map('items2dict')
      }}
    containers: |
      {{
        groups['containers'] |
          map('extract', hostvars) |
          map('dict2items') |
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) |
          map('items2dict')
      }}


