---

- hosts: app_dns:&servers
  vars_files: secrets.yml
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"
      force: "{{ proxmox_force | default(False) }}"

    containers:
    - vmid: 100
      hostname: "{{ 
        (groups['app_dns'] |
          intersect(groups['containers']) |
          map('extract', hostvars))[0].ns_name }}.{{ homelab_domain }}"
      ip_address: "{{ 
        (groups['app_dns'] |
          intersect(groups['containers']) |
          map('extract', hostvars))[0].ansible_host }}"
      disk: 'local-lvm:4'
      cores: 1
      memory: 512
      unprivileged: False

- hosts: app_dns:&containers
  roles:
  - role: dns
    domain: "{{ homelab_domain }}"
    dns: "{{ homelab_dns }}"
    servers: |
      {{
        groups['servers'] | 
          map('extract', hostvars) | 
          map('dict2items') | 
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) | 
          map('items2dict')
      }}
    containers: |
      {{
        groups['containers'] |
          map('extract', hostvars) |
          map('dict2items') |
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) |
          map('items2dict')
      }}


