---

- hosts: app_ai:&servers
  vars_files: secrets.yml
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"
      force: "{{ proxmox_force | default(False) }}"

    containers:
    - vmid: 102
      hostname: "{{ 
        (groups['app_ai'] |
          intersect(groups['containers']) |
          map('extract', hostvars))[0].ns_name }}.{{ homelab_domain }}"
      ip_address: "{{ (groups['app_ai'] |
          intersect(groups['containers']) |
          map('extract', hostvars))[0].ansible_host }}"
      disk: 'local-lvm:8'
      cores: 4
      memory: 4096
      unprivileged: True
      features:
        - nesting=1

- hosts: app_ai:&containers
  roles:
  - role: ramalama
    model: llama3.2:3b

