---

- hosts: role_dns
  roles:
  - role: dns
    domain: "{{ domain_name }}"
    dns: "{{ dns_config }}"
    servers: |
      {{
        groups['proxmox'] | 
          map('extract', hostvars) | 
          map('dict2items') | 
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) | 
          map('items2dict')
      }}
    containers: |
      {{
        groups['containers'] |
          map('extract', hostvars) |
          map('dict2items') |
          map('selectattr', 'key', 'in', ['ansible_host', 'ns_name']) |
          map('items2dict')
      }}


