---

- hosts: role_maruchan:&servers
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"
      domain: "{{ homelab_domain }}"

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"
      force: "{{ proxmox_force | default(True) }}"

    containers: "{{ 
      groups['role_maruchan'] |
        intersect(groups['containers']) |
        map('extract', hostvars) }}"

- hosts: role_maruchan:&containers
  roles:
  - role: maruchan
    config: "{{ maruchan_config }}"
    ai_url: "http://{{ 
      (groups['role_ai'] |
        intersect(groups['containers']) |
        map('extract', hostvars))[0].ns_name }}.{{ homelab_domain }}:8080"
    starbound_config:
      hostname: starbound
      port: 21026