---

- hosts: app_ai:&servers
  vars_files: secrets.yml
  roles:
  - role: proxmox_server

    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"
      domain: "{{ homelab_domain }}"

    proxmox:
      user: "root@pam"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"
      force: "{{ proxmox_force | default(True) }}"

    containers: "{{ 
      groups['app_ai'] |
        intersect(groups['containers']) |
        map('extract', hostvars) }}"

- hosts: app_ai:&containers
  roles:
  - role: ramalama
    model: llama3.2:3b

