---

- name: Setup dns hosts
  hosts: role_dns
  roles:
    - role: dns
      dns_servers: |
        {{
          groups['machines'] |
            map('extract', hostvars) |
            map('dict2items') |
            map('selectattr', 'key', 'in', ['ansible_host', 'hostname']) |
            map('items2dict')
        }}
      dns_containers: |
        {{
          groups['containers'] |
            map('extract', hostvars) |
            map('dict2items') |
            map('selectattr', 'key', 'in', ['dns_list']) |
            map('items2dict')
        }}

- name: Setup traefik hosts
  hosts: role_traefik
  roles:
    - role: traefik
      traefik_targets: |
        {{
          groups['all'] |
            map('extract', hostvars) |
            map('dict2items') |
            map('selectattr', 'key', 'in', ['hostname', 'traefik_config']) |
            map('items2dict')
        }}

- name: Setup wireguard hosts
  hosts: role_wgportal
  roles:
    - role: wgportal

- name: Setup forgejo hosts
  hosts: role_forgejo
  roles:
    - role: forgejo

- name: Setup semaphore hosts
  hosts: role_semaphore
  roles:
    - role: semaphore
