---

- hosts: homelab:&proxmox
  vars:
    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ gateway_ip }}"
      domain: "{{ domain_name }}"

    proxmox:
      user: "root@pam"
      node: "{{ hostname }}"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"

  roles:
  - role: proxmox_server

  tasks:
    - name: Build containers
      ansible.builtin.include_role:
        name: proxmox_server
        tasks_from: container
      vars:
        host_general: "{{ general }}"
        host_proxmox: "{{ proxmox }}"
        container: "{{ item }}"
        storage_target_path: "{{ 
          (groups['homelab'] |
            intersect(groups['role_storage']) |
            map('extract', hostvars))[0].storage_target_path }}"
      loop: "{{ 
        groups['homelab'] |
          intersect(groups['containers']) |
          map('extract', hostvars) }}"
