---

- hosts: homelab:&proxmox
  vars:
    general:
      pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      gateway: "{{ homelab_gateway_ip }}"
      domain: "{{ homelab_domain }}"

    proxmox:
      user: "root@pam"
      node: "{{ ns_name }}"
      host: "{{ ansible_host }}"
      password: "{{ proxmox_password }}"

  roles:
  - role: proxmox_server

  tasks:
    - name: Build containers
      ansible.builtin.include_role:
        name: proxmox_server
        tasks_from: container
      vars:
        host_general: "{{ general }}"
        host_proxmox: "{{ proxmox }}"
        container: "{{ item }}"
      loop: "{{ 
        groups['homelab'] |
          intersect(groups['containers']) |
          map('extract', hostvars) }}"
