- name: Stop existing {{ container.ns_name }}.{{ general.domain }}
  community.general.proxmox:
    vmid: '{{ container.vmid }}'
    node: root
    api_host: '{{ host_proxmox.host }}'
    api_user: '{{ host_proxmox.user }}'
    api_password: "{{ host_proxmox.password }}"
    state: stopped
  ignore_errors: True
  when: host_proxmox.force

- name: Remove if {{ container.ns_name }}.{{ general.domain }} exists
  community.general.proxmox:
    vmid: '{{ container.vmid }}'
    node: root
    api_host: '{{ host_proxmox.host }}'
    api_user: '{{ host_proxmox.user }}'
    api_password: "{{ host_proxmox.password }}"
    state: absent
  when: host_proxmox.force

- name: container {{ container.ns_name }}.{{ general.domain }} exists
  community.general.proxmox:
    vmid: '{{ container.vmid }}'
    node: root
    api_host: '{{ host_proxmox.host }}'
    api_user: '{{ host_proxmox.user }}'
    api_password: "{{ host_proxmox.password }}"
    hostname: "{{ container.ns_name }}.{{ general.domain }}"
    storage: local-lvm
    ostemplate: 'local:vztmpl/fedora-41-default_20241118_amd64.tar.xz'
    pubkey: "{{ host_general.pubkey | default(omit) }}"
    password: "{{ container.password | default(host_proxmox.password) }}"
    disk: '{{ container.disk | default(omit) }}'
    mounts: '{{ container.mounts | default(omit) }}'
    cores: '{{ container.cores | default(omit) }}'
    memory: '{{ container.memory | default(omit) }}'
    swap: 0
    unprivileged: '{{ container.unprivileged | default(omit) }}'
    features: '{{ container.features | default(omit) }}'
    onboot: True
    state: present
    netif:
      net0: "name=eth0,gw={{ general.gateway }},ip={{ container.ansible_host }}/24,bridge=vmbr0"

- name: container {{ container.ns_name }}.{{ general.domain }} is running
  community.general.proxmox:
    vmid: '{{ container.vmid }}'
    api_host: '{{ host_proxmox.host }}'
    api_user: '{{ host_proxmox.user }}'
    api_password: "{{ host_proxmox.password }}"
    state: started

- name: Check if ansible is installed on {{ container.ns_name }}.{{ general.domain }}
  ansible.builtin.shell: pct exec {{ container.vmid }} -- dnf list --installed -q openssh-server
  register: result
  ignore_errors: True
  changed_when: False

- name: Install ansible on {{ container.ns_name }}.{{ general.domain }}
  ansible.builtin.shell: |
    pct push {{ container.vmid }} /opt/setup.sh /opt/setup.sh
    pct exec {{ container.vmid }} -- chmod +x /opt/setup.sh
    pct exec {{ container.vmid }} -- /opt/setup.sh
  when: result is failed
