- name: Install forgejo and deps
  dnf:
    name:
    - forgejo
    - git
    - git-lfs
    - sqlite

- name: Unlock 'forgejo' user
  ansible.builtin.user:
    name: forgejo
    password_lock: false

- name: Add cap_net_bind_service to forgejo
  community.general.capabilities:
    path: /usr/bin/forgejo
    capability: cap_net_bind_service=ep
    state: present

- name: Upload sshd conf
  ansible.builtin.copy:
    src: 60-forgejo.conf
    dest: /etc/ssh/sshd_config.d/60-forgejo.conf
    mode: '0644'
  notify:
    - 'forgejo : Restart sshd service'

- name: Upload the test.app.ini file
  template:
    src: app.ini.j2
    dest: "/etc/forgejo/conf/test.app.ini"
    owner: root
    group: forgejo
    mode: '0640'
  register: ini_process

- name: Upload the app.ini file if test changed
  template:
    src: app.ini.j2
    dest: "/etc/forgejo/conf/app.ini"
    owner: root
    group: forgejo
    mode: '0660'
  when: ini_process is changed
  notify:
    - 'forgejo : Restart forgejo service'

- name: Start forgejo service
  service:
    name: forgejo.service
    enabled: true
    state: started

- name: Wait for server to exist
  ansible.builtin.wait_for:
    path: "/var/lib/forgejo/data/forgejo.db"
    state: present

- name: Wait until forgejo server is available
  uri:
    url: "{{ forgejo_config.app.server.protocol | default('http') }}://127.0.0.1:{{ forgejo_config.app.server.http_port | default(3000) }}"
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 2

- name: Check users
  shell: 
    "sudo -u forgejo forgejo \
      -w /var/lib/forgejo \
      -c /etc/forgejo/conf/app.ini \
      admin user list --admin | \
    awk '{print $2}' | \
    grep -w {{ forgejo_config.admin.username }}"
  register: admin_user_query
  changed_when: False
  ignore_errors: True

- name: Create user if it doesn't exist
  shell:
    "sudo -u forgejo forgejo \
      -w /var/lib/forgejo \
      -c /etc/forgejo/conf/app.ini \
      admin user create \
        --username {{ forgejo_config.admin.username }} \
        --password {{ forgejo_config.admin.password }} \
        --email {{ forgejo_config.admin.email }} \
        --admin"
  when: admin_user_query is failed
  no_log: True

- name: Change permissions
  file:
    path: "/etc/forgejo/conf/app.ini"
    state: file
    mode: "0640"
