---

- name: Prepare services
  ansible.builtin.dnf:
    name:
      - podman
      - ramalama

- name: Check if ramalama is running
  ansible.builtin.command: podman container inspect local_ai
  register: result
  ignore_errors: true
  changed_when: false

- name: Run ramalama
  ansible.builtin.command: >-
    ramalama serve -d
    -p 8080
    --name local_ai
    {{ ai_model | default('llama3.2:3b') }}
  changed_when: true
  when: result is failed
