---

- name: Prepare services
  dnf:
    name:
    - podman
    - git
    state: latest

- name: Download code
  ansible.builtin.git:
    repo: 'https://github.com/grillo-delmal/maruchan-discordbot.git'
    dest: /opt/maruchan-discordbot
    version: master

- name: Create directory
  ansible.builtin.file:
    path: /data/
    state: directory
    mode: '0755'

- name: Add config
  ansible.builtin.copy:
    dest: /data/config.json
    content: "{{ 
      config | 
        combine({'maruai':{'hostname': ai_url}}, recursive=True) |
        combine({'starbound': starbound_config}, recursive=True) |
        to_json(indent=4, sort_keys=True) }}"
    mode: '0644'
  register: config_change

- name: Build Image
  containers.podman.podman_image:
    name: localhost/maruchan
    path: /opt/maruchan-discordbot
  register: image_built

- name: Stop maruchan if image built
  containers.podman.podman_container:
    name: maruchan
    state: absent
  when: image_built is changed or config_change is changed

- name: Run maruchan
  containers.podman.podman_container:
    name: maruchan
    image: localhost/maruchan
    volumes:
      - "/data:/data:ro,Z"
    state: started