---

- name: Prepare services
  ansible.builtin.dnf:
    name:
      - python3.12
      - git
      - python3-pip

- name: Fix pip
  ansible.builtin.pip:
    name:
      - packaging

- name: Create virtual env
  ansible.builtin.shell:
    cmd: |
      python3.12 -m venv /opt/open-webui-venv
    creates:
      /opt/open-webui-venv

- name: Install open-webui
  ansible.builtin.pip:
    name: open-webui
    virtualenv: /opt/open-webui-venv
  notify:
    - 'openwebui : Restart open-webui service'

- name: Add open-webui.service
  ansible.builtin.copy:
    src: open-webui.service
    dest: /usr/lib/systemd/system/open-webui.service
    force: true
    mode: '0644'
  register: add_service_result

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: add_service_result is changed

- name: Configure bind
  ansible.builtin.template:
    src: open-webui.env.j2
    dest: /opt/open-webui.env

- name: Start open-webui
  ansible.builtin.service:
    name: open-webui.service
    enabled: true
    state: started
