---

- name: Restart minetest service
  service:
    name: minetest@{{ luanti_config.world.id }}.service
    state: restarted

- name: Restart mapserver service
  service:
    name: mapserver@{{ luanti_config.world.id }}.service
    state: restarted
