---

- name: Restart minetest service
  service:
    name: minetest@{{ world.id }}.service
    state: restarted

- name: Restart mapserver service
  service:
    name: mapserver@{{ world.id }}.service
    state: restarted
