---

- name: Prepare services
  dnf:
    name:
      - bind
    state: present

- name: Configure bind
  template:
    src: named.conf.j2
    dest: /etc/named.conf

- name: Check if raw zone changes
  template:
    src: main.zone.j2
    dest: /var/raw.main.zone
  vars:
    serial_num: '0'
  register: raw_zone

- name: Create real zone
  template:
    src: main.zone.j2
    dest: /var/named/{{ domain }}.zone
  vars:
    serial_num: >-
      {{
        ansible_date_time.year
      }}{{
        "%02d" % ( ansible_date_time.month | int )
      }}{{
        "%02d" % ( ansible_date_time.day | int )
      }}{{
        "%02d" % ( ansible_date_time.hour | int )
      }}
  when: raw_zone is changed
  notify:
    - 'dns : Restart named service'

- name: Get public IP
  ipify_facts:
    timeout: 15
  tags: ddns

- name: Set domain IP on CloudFlare
  cloudflare_dns:
    zone: "{{ base_domain_name }}"
    record: "{{ domain_name }}"
    type: A
    value: "{{ ipify_public_ip }}"
    api_token: "{{ cloudflare_token }}"
    proxied: "no"
    solo: "yes"
    state: present

- name: Set *.domain IP on CloudFlare
  cloudflare_dns:
    zone: "{{ base_domain_name }}"
    record: "*.{{ domain_name }}"
    type: A
    value: "{{ ipify_public_ip }}"
    api_token: "{{ cloudflare_token }}"
    proxied: "no"
    solo: "yes"
    state: present
  notify:
    - 'dns : Restart named service'

- name: BIND is started
  systemd:
    name: named.service
    state: started
    enabled: true
