---

- name: Prepare services
  dnf:
    name:
    - bind
    state: present

- name: Configure bind
  template:
    src: named.conf.j2
    dest: /etc/named.conf

- name: Check if raw zone changes
  template:
    src: main.zone.j2
    dest: /var/raw.main.zone
  vars:
    serial: '0'
  register: raw_zone

- name: Create real zone
  template:
    src: main.zone.j2
    dest: /var/named/{{ domain }}.zone
  vars:
    serial: '{{ ansible_date_time.year }}{{ "%02d" % ( ansible_date_time.month | int ) }}{{ "%02d" % ( ansible_date_time.day | int ) }}{{ "%02d" % ( ansible_date_time.hour | int ) }}'
  when: raw_zone is changed

- name: Start BIND
  systemd:
    name: named.service
    state: started
    enabled: True

