
- name: Get current info
  shell: "btrfs --format=json qgroup show -reF --iec {{ storage_btrfs_path }}{{ storage_data.path }}"
  register: output_text
  changed_when: False
  
- name: Get configured size
  shell: "echo {{ storage_data.size }} | numfmt --from=iec"
  register: expected_size
  changed_when: False
  when: "'size' in storage_data"

- name: Resize on existing size config
  shell: "btrfs qgroup limit {{ storage_data.size }} {{ (
        output_text.stdout | from_json
      )['qgroup-show'][0].qgroupid }} {{ storage_btrfs_path }}{{ storage_data.path }}"
  changed_when: False
  when: "'size' in storage_data and (
      (
        (
          output_text.stdout | from_json
        )['qgroup-show'][0].max_referenced | 
        int ) != ( expected_size.stdout | int )
    )"

- name: No limit when no size config
  shell: "btrfs qgroup limit 'none' {{ (
        output_text.stdout | from_json
      )['qgroup-show'][0].qgroupid }} {{ storage_btrfs_path }}{{ storage_data.path }}"
  changed_when: False
  when: "'size' not in storage_data and (
      (
        (
          output_text.stdout | from_json
        )['qgroup-show'][0].max_referenced 
      ) != 'none'
    )"