---

- name: Prepare services
  dnf:
    name:
    - btrfs
    - cockpit-files
    - cockpit-networkmanager
    - cockpit-storaged.noarch
    - nfs-utils
    - libnfsidmap
    - sssd-nfs-idmap
    state: latest

- name: Add group
  group:
    name: admin
    gid: 100000
    state: present

- name: Add user
  user:
    name: admin
    uid: 100000
    comment: admin
    group: admin

- name: Make sure they are subvolumes
  community.general.btrfs_subvolume:
    name: '{{ item.path }}'
  loop: '{{ storage_src }}'

- name: Make sure they have the correct size limits
  ansible.builtin.include_tasks:  btrfs_size.yml
  vars:
    storage_data: '{{ item }}'
  loop: '{{ storage_src }}'

- name: configure nfs server
  template: 
    src: exports.j2
    dest: /etc/exports
    mode: '0644'

- name: ensure nfs service is started
  service:
    name: nfs-server
    state: started