---

- name: Device is mounted with the correct options
  ansible.posix.mount:
    path: '{{ storage_btrfs_path }}'
    src: '{{ storage_btrfs_device }}'
    fstype: btrfs
    opts: rw,degraded
    state: present
  register: mount_options

- name: Remount now if options are not correct
  ansible.posix.mount:
    path: '{{ storage_btrfs_path }}'
    src: '{{ storage_btrfs_device }}'
    fstype: btrfs
    opts: rw,degraded
    state: remounted
  register: mount_options
  when: 'mount_options is changed'

- name: Prepare services
  dnf:
    name:
    - btrfs
    - cockpit-files
    - cockpit-networkmanager
    - cockpit-storaged
    - less
    - nfs-utils
    - libnfsidmap
    - sssd-nfs-idmap
    state: latest

- name: Add group
  group:
    name: admin
    gid: 100000
    state: present

- name: Add user
  user:
    name: admin
    uid: 100000
    comment: admin
    group: admin

- name: Make sure quotas are enabled
  shell: btrfs quota enable {{ storage_btrfs_path }}
  changed_when: False

- name: Make sure they are subvolumes
  community.general.btrfs_subvolume:
    name: '{{ item.path }}'
  loop: '{{ storage_src }}'

- name: Make sure they have the correct size limits
  ansible.builtin.include_tasks:  btrfs_size.yml
  vars:
    storage_data: '{{ item }}'
  loop: '{{ storage_src }}'

- name: configure nfs server
  template: 
    src: exports.j2
    dest: /etc/exports
    mode: '0644'
  register: config

- name: ensure nfs service is started
  service:
    name: nfs-server
    state: started
    enabled: True
  when: config is not changed

- name: ensure nfs service is started
  service:
    name: nfs-server
    state: restarted
    enabled: True
  when: config is changed
