- name: Check if path exist
  stat:
    path: '{{ storage_target_path }}{{ mount_data.path }}'
  register: register_name
  ignore_errors: True

- name: Path must exist
  ansible.builtin.file:
    path: '{{ storage_target_path }}{{ mount_data.path }}'
    state: directory
    mode: '0755'
  when: "'stat' in register_name and not register_name.stat.exists"