---
- name: Create storage paths
  ansible.builtin.include_tasks: nfs_paths.yml

- name: Mount an NFS volume
  ansible.posix.mount:
    src: '{{ storage_host }}:{{ storage_btrfs_path }}{{ mount_data.path }}'
    path: '{{ storage_target_path }}{{ mount_data.path }}'
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
