---

- name: Ensure mapserver directory exists
  file:
    path: /opt/mapserver
    state: directory

- name: Install mapserver
  unarchive:
    src: "https://github.com/minetest-mapserver/mapserver/releases/download/v4.9.1/mapserver_4.9.1_linux_amd64.tar.gz"
    dest: "/opt/mapserver/"
    owner: minetest
    group: minetest
    remote_src: yes

- name: Install mapserver service
  ansible.builtin.copy:
    src: mapserver@.service
    dest: "/etc/systemd/system/mapserver@.service"

- name: Get mapserver key
  shell: cat /opt/mapserver_key
  register: data
  ignore_errors: True
  changed_when: False

- name: Generate mapserver secretkey
  set_fact:
    mapserver_secretkey: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  when: data is failed

- name: Read mapserver secretkey
  set_fact:
    mapserver_secretkey: "{{ data.stdout }}"
  when: data is not failed

- name: Save generated key
  ansible.builtin.copy:
    dest: "/opt/mapserver_key"
    content: "{{ mapserver_secretkey }}"
    mode: 0600

