---

- name: Prepare services
  dnf:
    name:
      - podman
    state: latest

- name: Adding traefik.yml file
  template:
    src: traefik.yml.j2
    dest: "/opt/traefik.yml"
    mode: 0600
  notify:
    - 'traefik : Restart traefik container'

- name: Ensure directories are present
  file:
    path: '/opt/config/'
    state: directory
    mode: '0744'

- name: Adding dashboard file
  template:
    src: dashboard.yml.j2
    dest: "/opt/config/dashboard.yml"
    mode: 0600

- name: Adding config files to configured containers
  ansible.builtin.copy:
    dest: "/opt/config/{{ item.hostname }}-config.yml"
    content: "{{ item.traefik_config | to_yaml }}"
    mode: 0600
  when: "'traefik_config' in item"
  loop: '{{ targets }}'

- name: Remove config files for unconfigured containers
  file:
    dest: "/opt/config/{{ item.hostname }}-config.yml"
    state: absent
  when: "'traefik_config' not in item"
  loop: '{{ targets }}'

- name: Run traefik
  containers.podman.podman_container:
    name: traefik
    image: docker.io/library/traefik:latest
    ports:
      - "{{ (visible_host | split('/'))[0] }}:80:80"
      - "{{ (visible_host | split('/'))[0] }}:443:443"
    env:
      CF_API_EMAIL: '{{ letsencrypt_email }}'
      CF_DNS_API_TOKEN: '{{ cloudflare_token }}'
    volumes:
      - "/opt/traefik.yml:/etc/traefik/traefik.yml"
      - "/opt/config:/opt/config"
    state: started
