---
# yamllint disable rule:line-length
- name: Create TXT record
  when:
    - letsencrypt_dns01_provider == 'cloudflare'
    - letsencrypt_domain_name in r_acme_challenge.challenge_data
  community.general.cloudflare_dns:
    domain: "{{ base_domain_name }}"
    api_token: "{{ cloudflare_token }}"
    record: "{{ r_acme_challenge.challenge_data[letsencrypt_domain_name]['dns-01'].record }}"
    type: TXT
    value: "{{ r_acme_challenge.challenge_data[letsencrypt_domain_name]['dns-01'].resource_value }}"
    solo: true
    state: present
# yamllint enable rule:line-length
