---

- name: minetest server is installed
  dnf:
    name: minetest-server
    state: latest

- name: Patch 
  ansible.builtin.copy:
    src: minetest@.service
    dest: /usr/lib/systemd/system/minetest@.service
    force: true
    mode: '0644'

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: set minetest home valiable
  set_fact:
    mine_home: "/var/lib/minetest"

- name: Games folder exists
  file:
    path: "{{ mine_home }}/.minetest/games"
    state: directory
    owner: minetest
    group: minetest

- name: unzip is installed
  dnf:
    name: unzip
    state: latest
