---

- name: Check if path {{ btrfs_storage.path }}{{ mount_data_path }} exist
  stat:
    path: '{{ btrfs_storage.path }}{{ mount_data_path }}'
  register: register_name
  ignore_errors: True

- name: Path {{ btrfs_storage.path }}{{ mount_data_path }} must exist
  ansible.builtin.file:
    path: '{{ btrfs_storage.path }}{{ mount_data_path }}'
    state: directory
    mode: '0755'
  when: "'stat' in register_name and not register_name.stat.exists"